on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: "20.x"
    secrets:
      npm_token:
        required: true

jobs:
  publish-package:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ./dist

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: https://registry.npmjs.org/
          scope: '@lca_platform'
          always-auth: true
          token: ${{ secrets.npm_token }}
      
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}