name: Publish Helm Chart

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: arkitema.azurecr.io
      name:
        required: true
        type: string

    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build-image:
    name: Package and Push Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Render Chart
        run: helm template ${{ inputs.name }} .
        working-directory: helm

      - name: Package Chart
        run: helm package --version ${{ inputs.tag }} .
        working-directory: helm

      - name: Push Chart
        if: github.event_name != 'pull_request'
        run: helm push ${{ inputs.name }}-${{ inputs.tag }}.tgz oci://${{ inputs.registry }}/helm
        working-directory: helm
        env:
          HELM_EXPERIMENTAL_OCI: 1